language: node_js
node_js:
  - node
deploy:
  provider: npm
  email: npmjs@solsort.com
  api_key:
    secure: IaRUpKFMEooiZllg8egHSoa2drFfZQMIj9tAZziWTd75ivvbt+CmWel2DTlkrFHxZ2hWeao2HbyAmQXfd5IvKeZ91f8Sqm44I62X+Faj/upY9OXD8Z9Fi1yG3rVAMxDJHgombszfR79Y8keWqw+wZd48Lmy6+47wmfQx/jGUvQNyo+xe16NXMcpUZk/JI1f0eCJwK5vih3uuBa9qMAAKnug+EncUA24Q0Cuk4+3fLZtwrpLaZchO33HCzMqs3lS6t+5Sny2m3OtwSr78hGyO4Z3yrPvsBShglrKwUgkhpUefBbuk/gjFBH47mQTM1DGQCWQ369OTR5/BaFmdgtQbQ326HzPkjFKFTQTh9n7RveBoxRVWYgrN4nmq2NOQvLmRwpFsk7G359jswMB11BnNWhnT6QuETMMx4IY/wQOQHAdsmT1ihyPf6E3XCnKQBX6btHYIrIrNt3CVrzNG6i8t4zloQNU2vFjkzMKR1SpyIxvIroPPVmeYmXdVoodSHsRPhDymKztKxrxO5/mE72PWB0bOZkaztG/rdddGF3lWG59e600UBn67u9ZZS3rdsyrZ096W+ByFp4YbkQyAry9UEgfpkp0HKEmBkZnvE3AG9YNeGXI2CeOr90Dyhl/+Yb8GMiDli42vjUbO0S2v5d+D5Q8wVic+cDUHBu7bArktbgE=
  on:
    repo: solsort/direape
